# Generated by Django 3.2.13 on 2022-07-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_countrygeo_iso_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrygeo',
            name='is_removed',
        ),
    ]
